name: Nuitka tests
# makes little sense, spell-checker: disable
on:
  pull_request:
    branches:
      - develop
      - integration
  push:
    branches:
      - main
      - develop
      - integration
      - factory
      - release/**
      - hotfix/**

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  NUITKA_UPDATE_CHECK: "never"
  NUITKA_CACHE_DIR: ${{ github.workspace }}/.nuitka-cache

jobs:
  checks:
    runs-on: ubuntu-24.04
    name: Checks
    steps:
      - name: 🛎️ Checkout (Attempt 1)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout

      - name: ⏳ Wait for checkout retry 1
        if: steps.checkout.outcome == 'failure'
        run: sleep 120s
        shell: bash

      - name: 🛎️ Checkout (Attempt 2)
        if: steps.checkout.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout_retry_1

      - name: ⏳ Wait for checkout retry 2
        if: steps.checkout_retry_1.outcome == 'failure'
        run: sleep 300s
        shell: bash

      - name: 🛎️ Checkout (Attempt 3)
        if: steps.checkout_retry_1.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        id: checkout_retry_2

      - name: 🐍 Use Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: ⚡ Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: ♻️ Restore Nuitka tool data
        id: restore-nuitka-tool-cache
        uses: actions/cache/restore@v4
        with:
          path: .nuitka-cache
          key: nuitka-cache-${{ runner.os }}-${{ runner.arch }}-checks-${{ github.ref_name }}
          restore-keys: |
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-checks-
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-

      - name: 🧳 Install Nuitka and dependencies
        run: |
          export UV_PROJECT_ENVIRONMENT="$RUNNER_TEMP/nuitka-venv"
          echo "UV_PROJECT_ENVIRONMENT=$UV_PROJECT_ENVIRONMENT" >> "$GITHUB_ENV"
          uv sync --dev --frozen --no-install-project --python python
          echo "$UV_PROJECT_ENVIRONMENT/bin" >> "$GITHUB_PATH"

      - name: 🔎 PyLint on Nuitka source code
        run: |
          uv run --frozen --with pylint==4.0.5 python -m nuitka.tools.quality.pylint --assume-yes-for-downloads

      - name: 🔎 RestLint on Nuitka source code
        run: |
          uv run --frozen python -m nuitka.tools.quality.restlint --assume-yes-for-downloads

      - name: 🔎 YamlLint on Nuitka source code
        run: |
          uv run --frozen python -m nuitka.tools.quality.yamllint --assume-yes-for-downloads

      - name: 🔎 Codespell on Nuitka source code
        run: |
          uv run --frozen python -m nuitka.tools.quality.codespell --assume-yes-for-downloads

      - name: 🔎 Auto-format check on Nuitka source code
        run: |
          uv run --frozen python -m nuitka.tools.quality.auto_format --check-only --assume-yes-for-downloads

      - name: ♻️ Save Nuitka tool data
        if: always() && steps.restore-nuitka-tool-cache.outputs.cache-hit != 'true'
        continue-on-error: true
        uses: actions/cache/save@v4
        with:
          path: .nuitka-cache
          key: ${{ steps.restore-nuitka-tool-cache.outputs.cache-primary-key }}

      - name: 🔎 Specialized C code check
        run: |
          python ./bin/generate-specialized-c-code --check

      - name: 🔎 Specialized Python code check
        run: |
          python ./bin/generate-specialized-python-code --check

  linux:
    needs: checks
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python_version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    name: Ubuntu Python ${{ matrix.python_version }}
    steps:
      - name: 🛎️ Checkout (Attempt 1)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout

      - name: ⏳ Wait for checkout retry 1
        if: steps.checkout.outcome == 'failure'
        run: sleep 120s
        shell: bash

      - name: 🛎️ Checkout (Attempt 2)
        if: steps.checkout.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout_retry_1

      - name: ⏳ Wait for checkout retry 2
        if: steps.checkout_retry_1.outcome == 'failure'
        run: sleep 300s
        shell: bash

      - name: 🛎️ Checkout (Attempt 3)
        if: steps.checkout_retry_1.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        id: checkout_retry_2

      - name: 🐍 Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: ⚡ Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: ♻️ Cache Nuitka tool data
        uses: actions/cache@v4
        with:
          path: .nuitka-cache
          key: nuitka-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python_version }}-${{ github.ref_name }}
          restore-keys: |
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python_version }}-
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-

      - name: ♻️ Install cached APT packages
        uses: awalsh128/cache-apt-pkgs-action@v1.6.1
        with:
          packages: patchelf gdb ccache libfuse2
          version: ubuntu-24.04
          execute_install_scripts: true

      - name: 🧳 Install Nuitka and dependencies
        run: |
          export UV_PROJECT_ENVIRONMENT="$RUNNER_TEMP/nuitka-venv"
          echo "UV_PROJECT_ENVIRONMENT=$UV_PROJECT_ENVIRONMENT" >> "$GITHUB_ENV"
          uv sync --no-dev --frozen --no-install-project --python python
          uv pip install --python "$UV_PROJECT_ENVIRONMENT" --no-deps .
          echo "$UV_PROJECT_ENVIRONMENT/bin" >> "$GITHUB_PATH"

      - name: ⚙️ Verbose scons output in compilation
        run: |
          set -x
          python -m nuitka --mode=module --show-scons --run --report=compilation-report-module.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=accelerated --show-scons --run --report=compilation-report-accelerated.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=standalone --show-scons --run --report=compilation-report-standalone.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          readelf -d EmptyModuleTest.dist/EmptyModuleTest.bin | tee standalone-binary-readelf.txt
          ldd EmptyModuleTest.dist/EmptyModuleTest.bin | tee standalone-binary-ldd.txt
          python -m nuitka --mode=onefile --show-scons --run --report=compilation-report-onefile.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
        shell: bash

      - name: 📤 Archive compilation reports for empty modules
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compilation-reports-${{ runner.os }}-${{ matrix.python_version }}
          path: |
            *.xml
            standalone-binary-readelf.txt
            standalone-binary-ldd.txt

      # This can be used to ssh into GitHub actions if debugging is needed.
      # - uses: actions/checkout@v4
      # - name: Setup upterm session
      #   uses: lhotari/action-upterm@v1
      #   with:
      #     ## limits ssh access and adds the ssh public keys of the listed GitHub users
      #     limit-access-to-users: kayhayen

      - name: 🧪 Run Nuitka test suite
        run: |
          python -m nuitka --version
          env | sort
          python ./tests/run-tests --no-other-python --skip-reflection-test --skip-all-cpython-tests --assume-yes-for-downloads

  mac-python3:
    needs: checks
    runs-on: macos-latest
    strategy:
      matrix:
        python_version:
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    name: macOS Python ${{ matrix.python_version }}
    steps:
      - name: 🛎️ Checkout (Attempt 1)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout

      - name: ⏳ Wait for checkout retry 1
        if: steps.checkout.outcome == 'failure'
        run: sleep 120s
        shell: bash

      - name: 🛎️ Checkout (Attempt 2)
        if: steps.checkout.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout_retry_1

      - name: ⏳ Wait for checkout retry 2
        if: steps.checkout_retry_1.outcome == 'failure'
        run: sleep 300s
        shell: bash

      - name: 🛎️ Checkout (Attempt 3)
        if: steps.checkout_retry_1.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        id: checkout_retry_2

      - name: 🐍 Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: ⚡ Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: ♻️ Cache Nuitka tool data
        uses: actions/cache@v4
        with:
          path: .nuitka-cache
          key: nuitka-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python_version }}-${{ github.ref_name }}
          restore-keys: |
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python_version }}-
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-

      - name: ⚙️ Verbose installation output for Python
        run: |
          set -x
          which python
          otool -L "$(which python)"
          otool -l "$(which python)"
          ls -lR "$(dirname "$(dirname "$(which python)")")"

      - name: 🧳 Install Nuitka and dependencies
        run: |
          export UV_PROJECT_ENVIRONMENT="$RUNNER_TEMP/nuitka-venv"
          echo "UV_PROJECT_ENVIRONMENT=$UV_PROJECT_ENVIRONMENT" >> "$GITHUB_ENV"
          uv sync --no-dev --frozen --no-install-project --python python
          uv pip install --python "$UV_PROJECT_ENVIRONMENT" --no-deps .
          echo "$UV_PROJECT_ENVIRONMENT/bin" >> "$GITHUB_PATH"

      - name: Verbose scons output in compilation
        run: |
          set -x

          cleanupEmptyModuleOutputs() {
            rm -rf EmptyModuleTest EmptyModuleTest.*
          }

          retryMacCompileCommand() {
            cleanupEmptyModuleOutputs

            if "$@"; then
              return 0
            fi

            echo "Retrying once after 30 seconds to tolerate a transient macOS runner failure."
            sleep 30

            cleanupEmptyModuleOutputs

            "$@"
            return $?
          }

          retryMacCompileCommand python -m nuitka --mode=module --show-scons --run --report=compilation-report-module.xml --assume-yes-for-downloads tests/basics/EmptyModuleTest.py
          retryMacCompileCommand python -m nuitka --mode=accelerated --show-scons --run --report=compilation-report-accelerated.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          retryMacCompileCommand python -m nuitka --mode=standalone --show-scons --run --report=compilation-report-standalone.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          retryMacCompileCommand python -m nuitka --mode=onefile --show-scons --run --report=compilation-report-onefile.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py

          # DLL mode has no run ability at this time.
          retryMacCompileCommand python -m nuitka --mode=dll --show-scons --report=compilation-report-dll.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
        shell: bash

      - name: Archive compilation reports for empty modules
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compilation-reports-${{ runner.os }}-${{ matrix.python_version }}
          path: |
            *.xml

      - name: 🐞 Check all modes for debug output
        run: |
          set -x
          python -m nuitka --mode=module --run --report=compilation-report-module.xml --debug --assume-yes-for-downloads tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=accelerated --run --report=compilation-report-accelerated.xml --debug --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=standalone --run --report=compilation-report-standalone.xml --debug --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=onefile --run --report=compilation-report-onefile.xml --debug --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py

          # DLL mode has no run ability at this time.
          python -m nuitka --mode=dll --report=compilation-report-onefile.xml --debug --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
        shell: bash

      - name: Run Nuitka test suite
        run: |
          python -m nuitka --version
          env | sort
          python ./tests/run-tests --no-other-python --skip-reflection-test --skip-all-cpython-tests --assume-yes-for-downloads

  windows:
    needs: checks
    runs-on: windows-latest
    strategy:
      matrix:
        python_version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    name: Windows Python ${{ matrix.python_version }}
    steps:
      - name: 🛎️ Checkout (Attempt 1)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout

      - name: ⏳ Wait for checkout retry 1
        if: steps.checkout.outcome == 'failure'
        run: sleep 120s
        shell: bash

      - name: 🛎️ Checkout (Attempt 2)
        if: steps.checkout.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout_retry_1

      - name: ⏳ Wait for checkout retry 2
        if: steps.checkout_retry_1.outcome == 'failure'
        run: sleep 300s
        shell: bash

      - name: 🛎️ Checkout (Attempt 3)
        if: steps.checkout_retry_1.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        id: checkout_retry_2

      - name: 🐍 Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: ⚡ Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: ♻️ Cache Nuitka tool data
        uses: actions/cache@v4
        with:
          path: .nuitka-cache
          key: nuitka-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python_version }}-${{ github.ref_name }}
          restore-keys: |
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python_version }}-
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-

      - uses: ilammy/msvc-dev-cmd@v1

      - name: 🧳 Install Nuitka and dependencies
        run: |
          $env:UV_PROJECT_ENVIRONMENT = "$env:RUNNER_TEMP\nuitka-venv"
          "UV_PROJECT_ENVIRONMENT=$env:UV_PROJECT_ENVIRONMENT" | Out-File -FilePath $env:GITHUB_ENV -Append
          uv sync --no-dev --frozen --no-install-project --python python
          uv pip install --python $env:UV_PROJECT_ENVIRONMENT --no-deps .
          "$env:UV_PROJECT_ENVIRONMENT\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Verbose scons output in compilation
        run: |
          set -x
          python -m nuitka --mode=module --show-scons --run --report=compilation-report-module.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=accelerated --show-scons --run --report=compilation-report-accelerated.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=standalone --show-scons --run --report=compilation-report-standalone.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=onefile --show-scons --run --report=compilation-report-onefile.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
        shell: bash

      - name: Archive compilation reports for empty modules
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compilation-reports-${{ runner.os }}-${{ matrix.python_version }}
          path: |
            *.xml

      - name: Run Nuitka test suite
        run: |
          Get-ChildItem env:
          python -m nuitka --version
          python .\tests\run-tests --no-other-python --no-debug --skip-reflection-test --skip-all-cpython-tests --assume-yes-for-downloads

  windows-arm:
    needs: checks
    runs-on: windows-11-arm
    strategy:
      matrix:
        python_version:
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"
    name: Windows ARM Python ${{ matrix.python_version }}
    steps:
      - name: 🛎️ Checkout (Attempt 1)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout

      - name: ⏳ Wait for checkout retry 1
        if: steps.checkout.outcome == 'failure'
        run: sleep 120s
        shell: bash

      - name: 🛎️ Checkout (Attempt 2)
        if: steps.checkout.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        continue-on-error: true
        id: checkout_retry_1

      - name: ⏳ Wait for checkout retry 2
        if: steps.checkout_retry_1.outcome == 'failure'
        run: sleep 300s
        shell: bash

      - name: 🛎️ Checkout (Attempt 3)
        if: steps.checkout_retry_1.outcome == 'failure'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: false
          filter: blob:none
        id: checkout_retry_2

      - name: 🐍 Use Python ${{ matrix.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python_version }}

      - name: ⚡ Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: ♻️ Cache Nuitka tool data
        uses: actions/cache@v4
        with:
          path: .nuitka-cache
          key: nuitka-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python_version }}-${{ github.ref_name }}
          restore-keys: |
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-${{ matrix.python_version }}-
            nuitka-cache-${{ runner.os }}-${{ runner.arch }}-

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: arm64

      - name: 🧳 Install Nuitka and dependencies
        run: |
          $env:UV_PROJECT_ENVIRONMENT = "$env:RUNNER_TEMP\nuitka-venv"
          "UV_PROJECT_ENVIRONMENT=$env:UV_PROJECT_ENVIRONMENT" | Out-File -FilePath $env:GITHUB_ENV -Append
          uv sync --no-dev --frozen --no-install-project --python python
          uv pip install --python $env:UV_PROJECT_ENVIRONMENT --no-deps .
          "$env:UV_PROJECT_ENVIRONMENT\Scripts" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: Verbose scons output in compilation
        run: |
          set -x
          python -m nuitka --mode=module --show-scons --run --report=compilation-report-module.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=accelerated --show-scons --run --report=compilation-report-accelerated.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=standalone --show-scons --run --report=compilation-report-standalone.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
          python -m nuitka --mode=onefile --show-scons --run --report=compilation-report-onefile.xml --assume-yes-for-downloads --experimental=debug-report-traceback tests/basics/EmptyModuleTest.py
        shell: bash

      - name: Archive compilation reports for empty modules
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: compilation-reports-${{ runner.os }}-arm64-${{ matrix.python_version }}
          path: |
            *.xml

      - name: Run Nuitka test suite
        run: |
          Get-ChildItem env:
          python -m nuitka --version
          python .\tests\run-tests --no-other-python --no-debug --skip-reflection-test --skip-all-cpython-tests --assume-yes-for-downloads
